"""vote table for voting statemnet auto geneated by alembic through --autogenerate

Revision ID: 68815715b484
Revises: 6b6dd915a149
Create Date: 2022-02-20 16:43:33.580135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68815715b484'
down_revision = '6b6dd915a149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'github_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'github_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('votes')
    # ### end Alembic commands ###
